# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Substrate Connect - Deploy Projects

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Checkout gh-pages branch
      run:
        rm -rf _site
        git worktree add _site -f gh-pages
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Deploy
      run:         
          mkdir -p ./_site/burnr
          mkdir -p ./_site/smoldot-browser-demo
          mkdir -p ./_site/multiple-network-demo
          mkdir -p ./_site/extension
          touch ./_site/.nojekyll
          echo "Place burnr wallet demo's files."
          cp -r ./projects/burnr/dist/* ./$directory/burnr/.
          echo "Place Smoldot browser demo's files."
          cp -r ./projects/smoldot-browser-demo/dist/* ./$directory/smoldot-browser-demo/.
          echo "Place Multiple network demo's files."
          cp -r ./projects/multiple-network-demo/dist/* ./$directory/multiple-network-demo/.
          echo "Place Substrate-connect extension's zip."
          cp ./projects/extension/dist/substrate-connect.zip ./$directory/extension/substrate-connect.zip
          echo "Place landing page's files."
          cp -r ./projects/landing-page/dist/* ./$directory/.
          echo "Generate API docs."
          yarn api-docs
          echo -e "\033[0;32mDeleting old content...\033[0m"

    - uses: actions/checkout@v2
      with: 
        ref: 'gh-pages'
    - uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
      id: ipfs-upload
      with:
        pin-name: 'substrate-connect'
        path: '.'
        pinata-api-key: ${{ secrets.PINATA_KEY }}
        pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
        remove-old: true
      # only:
      #   - master
    - run: |
        echo "Uploaded hash: ${{ steps.ipfs-upload.outputs.hash }}"
